version: "3.9"

services:
  # -------------------- PROXY --------------------
  proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - registration-service
      - view-service
    networks:
      - frontend

  # ---------------- REGISTRATION SERVICE ----------------
  registration-service:
    build: ./registration-service
    expose:
      - "3000"
    depends_on:
      - db
    networks:
      - frontend
      - backend
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=studentdb

  # ------------------ VIEW SERVICE ------------------
  view-service:
    build: ./view-service
    expose:
      - "3001"
    depends_on:
      - db
    networks:
      - frontend
      - backend
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=studentdb

  # ---------------------- DATABASE ----------------------
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studentdb
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

# ---------------------- NETWORKS ----------------------
networks:
  frontend:
  backend:

# ---------------------- VOLUMES -----------------------
volumes:
  db_data:

